"""
Tests for LocalEmbedder (ModelReduce Session 2 hardening).

LocalEmbedder wraps Ollama's embedding endpoint for semantic similarity.
Tests use a fake embedder (deterministic vectors) so they run without
Ollama; a live test is skip-guarded.
"""
import math
import pytest

from knowledge_graph_pkg.embeddings import cosine_similarity, EmbeddingCache


def test_cosine_identical_is_one():
    v = [0.1, 0.2, 0.3, 0.4]
    assert abs(cosine_similarity(v, v) - 1.0) < 1e-9


def test_cosine_orthogonal_is_zero():
    assert abs(cosine_similarity([1.0, 0.0], [0.0, 1.0])) < 1e-9


def test_cosine_opposite_is_negative():
    assert cosine_similarity([1.0, 0.0], [-1.0, 0.0]) < 0


def test_cosine_handles_zero_vector():
    # zero-norm must not raise; defined as 0 similarity
    assert cosine_similarity([0.0, 0.0], [1.0, 1.0]) == 0.0


def test_embedding_cache_memoizes():
    calls = {"n": 0}

    def fake_embed_one(text):
        calls["n"] += 1
        return [float(len(text)), 1.0]

    cache = EmbeddingCache(fake_embed_one)
    a = cache.get("hello")
    b = cache.get("hello")
    assert a == b
    assert calls["n"] == 1  # second call served from cache
    cache.get("world")
    assert calls["n"] == 2


# ---------- live test (skipped unless Ollama + embed model present) ----------

def _ollama_up():
    try:
        import urllib.request
        urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=2)
        return True
    except Exception:
        return False


def _ollama_importable():
    try:
        import ollama  # noqa: F401
        return True
    except Exception:
        return False


def _embed_model_available():
    return _ollama_importable() and _ollama_up()


@pytest.mark.skipif(not _embed_model_available(),
                    reason="No Ollama embedding model available")
def test_live_local_embedder():
    from knowledge_graph_pkg.embeddings import LocalEmbedder
    emb = LocalEmbedder()
    a = emb.embed_one("Mitochondria produce ATP")
    b = emb.embed_one("ATP is generated by mitochondria")
    c = emb.embed_one("The Eiffel Tower is in Paris")
    # paraphrase should be more similar than unrelated sentence
    assert cosine_similarity(a, b) > cosine_similarity(a, c)
