"""
Local semantic embeddings via Ollama (ModelReduce Session 2 hardening).

Cross-model verification needs to recognize that "Mitochondria produce ATP"
and "ATP is generated by mitochondria" are the *same fact*. Word-overlap
(Jaccard) cannot -- it sees different tokens. Semantic embeddings can.

:class:`LocalEmbedder` wraps Ollama's embedding endpoint (default
``mxbai-embed-large``); :func:`cosine_similarity` scores two vectors;
:class:`EmbeddingCache` memoizes embeddings so clustering doesn't re-embed
the same statement repeatedly.

Ollama is an optional dependency (the ``model-reduce`` extra). The cross
model verifier falls back to Jaccard + exact-SPO matching when no embedder
is available, so this module is never required for the package to work.
"""

import math
from typing import Any, Callable, Dict, List, Optional


def cosine_similarity(a: List[float], b: List[float]) -> float:
    """Cosine similarity of two equal-length vectors, in ``[-1, 1]``.

    Returns 0.0 if either vector has zero norm (undefined direction) rather
    than raising, so callers can treat it as "no similarity".
    """
    if not a or not b:
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return dot / (na * nb)


class EmbeddingCache:
    """Memoize an embed-one function so repeated texts cost nothing."""

    def __init__(self, embed_one: Callable[[str], List[float]]):
        self._embed_one = embed_one
        self._cache: Dict[str, List[float]] = {}

    def get(self, text: str) -> List[float]:
        if text not in self._cache:
            self._cache[text] = self._embed_one(text)
        return self._cache[text]


class OllamaEmbedder:
    """Semantic embeddings from a local Ollama embedding model."""

    def __init__(self, model: str = "mxbai-embed-large",
                 host: str = "http://localhost:11434"):
        try:
            import ollama
        except ImportError as exc:  # pragma: no cover - needs the extra
            raise ImportError(
                "OllamaEmbedder requires the model-reduce extra: "
                "pip install knowledgereduce[model-reduce]"
            ) from exc
        self._ollama = ollama
        self.client = ollama.Client(host=host)
        self.model = model
        self._cache = EmbeddingCache(self._embed_one_uncached)

    def _embed_one_uncached(self, text: str) -> List[float]:
        resp = self.client.embeddings(model=self.model, prompt=text)
        # ollama client returns a mapping or object with 'embedding'
        if isinstance(resp, dict):
            return list(resp.get("embedding") or [])
        return list(getattr(resp, "embedding", []) or [])

    def embed_one(self, text: str) -> List[float]:
        """Return the (cached) embedding vector for ``text``."""
        return self._cache.get(text)

    def embed(self, texts: List[str]) -> List[List[float]]:
        """Embed a list of texts (cached per text)."""
        return [self.embed_one(t) for t in texts]

    def similarity(self, a: str, b: str) -> float:
        """Cosine similarity between the embeddings of two texts."""
        return cosine_similarity(self.embed_one(a), self.embed_one(b))


class SentenceTransformersEmbedder:
    """Offline semantic embeddings from a local sentence-transformers model."""

    def __init__(self, model: str = "all-MiniLM-L6-v2"):
        try:
            from sentence_transformers import SentenceTransformer
        except ImportError as exc:
            raise ImportError(
                "SentenceTransformersEmbedder requires the sentence-transformers extra: "
                "pip install knowledgereduce[sentence-transformers]"
            ) from exc
        self.model = model
        self.client = SentenceTransformer(model)
        self._cache = EmbeddingCache(self._embed_one_uncached)

    def _embed_one_uncached(self, text: str) -> List[float]:
        import numpy as np
        vector = self.client.encode(text, convert_to_numpy=True)
        return [float(x) for x in vector]

    def embed_one(self, text: str) -> List[float]:
        """Return the (cached) embedding vector for ``text``."""
        return self._cache.get(text)

    def embed(self, texts: List[str]) -> List[List[float]]:
        """Embed a list of texts (cached per text)."""
        return [self.embed_one(t) for t in texts]

    def similarity(self, a: str, b: str) -> float:
        """Cosine similarity between the embeddings of two texts."""
        return cosine_similarity(self.embed_one(a), self.embed_one(b))


# Backward-compatible alias
LocalEmbedder = OllamaEmbedder


def get_embedder(embedder_type: str, model: Optional[str] = None, **kwargs) -> Any:
    """Factory function to instantiate the correct embeddings backend."""
    embedder_type = embedder_type.lower()
    if embedder_type == "ollama":
        return OllamaEmbedder(
            model=model or "mxbai-embed-large",
            host=kwargs.get("host", "http://localhost:11434")
        )
    elif embedder_type == "sentence-transformers":
        return SentenceTransformersEmbedder(
            model=model or "all-MiniLM-L6-v2"
        )
    else:
        raise ValueError(f"Unknown embedder type: {embedder_type}")


class VectorIndex:
    """NumPy-vectorized similarity search index for fast cosine matching."""

    def __init__(self):
        import numpy as np
        self._np = np
        self.ids: List[str] = []
        self.vectors: List[List[float]] = []
        self._matrix = None
        self._norms = None

    def add_vector(self, vector_id: str, vector: List[float]) -> None:
        """Add a vector to the index. Invalidates built matrix."""
        if vector_id in self.ids:
            idx = self.ids.index(vector_id)
            self.vectors[idx] = vector
        else:
            self.ids.append(vector_id)
            self.vectors.append(vector)
        self._matrix = None
        self._norms = None

    def remove_vector(self, vector_id: str) -> None:
        """Remove a vector from the index by ID."""
        if vector_id in self.ids:
            idx = self.ids.index(vector_id)
            self.ids.pop(idx)
            self.vectors.pop(idx)
            self._matrix = None
            self._norms = None

    def _build(self) -> None:
        """Construct/cache the numpy matrix and precompute L2 norms."""
        if not self.vectors:
            self._matrix = self._np.zeros((0, 0))
            self._norms = self._np.zeros((0,))
            return
        self._matrix = self._np.array(self.vectors, dtype=self._np.float32)
        self._norms = self._np.linalg.norm(self._matrix, axis=1)
        self._norms[self._norms == 0.0] = 1.0

    def query(self, query_vector: List[float], top_k: int = 5) -> List[tuple]:
        """Search the index for the most similar vectors.

        Returns:
            List of (vector_id, similarity_score) sorted descending.
        """
        if not self.vectors:
            return []
        
        if self._matrix is None:
            self._build()

        np = self._np
        q = np.array(query_vector, dtype=np.float32)
        q_norm = np.linalg.norm(q)
        if q_norm == 0.0:
            return [(vid, 0.0) for vid in self.ids[:top_k]]

        dot_products = np.dot(self._matrix, q)
        similarities = dot_products / (self._norms * q_norm)
        sorted_indices = np.argsort(similarities)[::-1]
        
        results = []
        for idx in sorted_indices[:top_k]:
            results.append((self.ids[idx], float(similarities[idx])))
        return results

