"""
Local semantic embeddings via Ollama (ModelReduce Session 2 hardening).

Cross-model verification needs to recognize that "Mitochondria produce ATP"
and "ATP is generated by mitochondria" are the *same fact*. Word-overlap
(Jaccard) cannot -- it sees different tokens. Semantic embeddings can.

:class:`LocalEmbedder` wraps Ollama's embedding endpoint (default
``mxbai-embed-large``); :func:`cosine_similarity` scores two vectors;
:class:`EmbeddingCache` memoizes embeddings so clustering doesn't re-embed
the same statement repeatedly.

Ollama is an optional dependency (the ``model-reduce`` extra). The cross
model verifier falls back to Jaccard + exact-SPO matching when no embedder
is available, so this module is never required for the package to work.
"""

import math
from typing import Callable, Dict, List, Optional


def cosine_similarity(a: List[float], b: List[float]) -> float:
    """Cosine similarity of two equal-length vectors, in ``[-1, 1]``.

    Returns 0.0 if either vector has zero norm (undefined direction) rather
    than raising, so callers can treat it as "no similarity".
    """
    if not a or not b:
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return dot / (na * nb)


class EmbeddingCache:
    """Memoize an embed-one function so repeated texts cost nothing."""

    def __init__(self, embed_one: Callable[[str], List[float]]):
        self._embed_one = embed_one
        self._cache: Dict[str, List[float]] = {}

    def get(self, text: str) -> List[float]:
        if text not in self._cache:
            self._cache[text] = self._embed_one(text)
        return self._cache[text]


class LocalEmbedder:
    """Semantic embeddings from a local Ollama embedding model."""

    def __init__(self, model: str = "mxbai-embed-large",
                 host: str = "http://localhost:11434"):
        try:
            import ollama
        except ImportError as exc:  # pragma: no cover - needs the extra
            raise ImportError(
                "LocalEmbedder requires the model-reduce extra: "
                "pip install knowledgereduce[model-reduce]"
            ) from exc
        self._ollama = ollama
        self.client = ollama.Client(host=host)
        self.model = model
        self._cache = EmbeddingCache(self._embed_one_uncached)

    def _embed_one_uncached(self, text: str) -> List[float]:
        resp = self.client.embeddings(model=self.model, prompt=text)
        # ollama client returns a mapping or object with 'embedding'
        if isinstance(resp, dict):
            return list(resp.get("embedding") or [])
        return list(getattr(resp, "embedding", []) or [])

    def embed_one(self, text: str) -> List[float]:
        """Return the (cached) embedding vector for ``text``."""
        return self._cache.get(text)

    def embed(self, texts: List[str]) -> List[List[float]]:
        """Embed a list of texts (cached per text)."""
        return [self.embed_one(t) for t in texts]

    def similarity(self, a: str, b: str) -> float:
        """Cosine similarity between the embeddings of two texts."""
        return cosine_similarity(self.embed_one(a), self.embed_one(b))
